apiVersion: v1
kind: Pod
metadata:
  name: fruit-service
spec:
  containers:
  - name: legacy-fruit-services
    image: linuxacademycontent/legacy-fruit-service:1
  - name: haproxy-ambassdor
    image: haproxy:1.7
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /usr/local/etc/haproxy
        name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: fruit-service-ambassador-config